feat: add Hex2Vec embedder
srai-lab/srai pull request #236
Opened 2023-04-24 19:02 UTC by simonusher

2023-04-26 14:29 UTC, piotrgramacki commented on srai/embedders/hex2vec/embedder.py
> +            encoder_sizes = [150, 75, 50]
Maybe extract those defaults to constant?

2023-04-26 14:29 UTC, piotrgramacki commented on srai/embedders/hex2vec/neighbour_dataset.py
> +        seed: Optional[int] = None,
Remove `seed` and use `np.random.randint`?

2023-04-26 15:26 UTC, piotrgramacki submitted a review, later dismissed

2023-04-26 15:39 UTC, piotrgramacki approved these changes

2023-04-26 16:58 UTC, RaczeQ commented on srai/embedders/hex2vec/embedder.py
> +        self._model = Hex2VecModel(layer_sizes=[num_features, *self._encoder_sizes])
We can't setup learning rate even as `**hex2vec_model_kwargs` in init, do we want to leave it like that?

2023-04-26 17:01 UTC, RaczeQ submitted a review, later dismissed
I really like current variables naming. It's really clear to follow 🥇

2023-04-26 17:16 UTC, piotrgramacki approved these changes

2023-04-26 17:24 UTC, Calychas commented
Add an example with some clustering or other visualizations (RGB)

2023-04-26 21:33 UTC, Calychas commented on tests/embedders/hex2vec/generation.py
> +from srai.loaders.osm_loaders.filters.osm_tags_type import osm_tags_type
```suggestion
from srai.loaders.osm_loaders.filters import osm_tags_type
```

2023-04-26 21:45 UTC, Calychas requested changes
Please add Hex2Vec to `tests/miscellaneous/test_optional_dependencies.py` -> `test_torch()`

2023-04-26 21:45 UTC, Calychas commented on tests/embedders/hex2vec/generation.py
> +def generate_test_case(
This function is not used at all. I understand that it can be used in the future to generate new use cases, but should we actually keep it?

2023-04-26 21:45 UTC, Calychas commented on tests/embedders/hex2vec/test_neighbour_dataset.py
> +    mocker: MockerFixture = request.getfixturevalue("mocker")
```suggestion
def test_raises_with_incorrect_sample_k_distance(
    negative_sample_k_distance: int, expectation: Any, request: Any, mocker: MockerFixture
) -> None:
    """Test if NeighbourDataset checks negative_sample_k_distance correctness."""
```

2023-04-26 21:45 UTC, Calychas commented on tests/embedders/hex2vec/test_neighbour_dataset.py
> +    data_df = request.getfixturevalue("regions_data_df")
```suggestion
@pytest.mark.parametrize("negative_sample_k_distance", [2, 3, 4])  # type: ignore
def test_lookup_tables_construction(negative_sample_k_distance: int, request: Any, regions_data_df: pd.DataFrame):
    """Test if NeighbourDataset constructs lookup tables correctly."""
```

2023-04-26 21:45 UTC, Calychas commented on srai/embedders/hex2vec/embedder.py
> +        trainer = pl.Trainer(**trainer_kwargs)
I think this will throw an error on `trainer_kwargs=None`

2023-04-27 19:41 UTC, piotrgramacki submitted a review, later dismissed

2023-04-27 20:10 UTC, piotrgramacki approved these changes

2023-04-27 20:11 UTC, merged