Improve docs
srai-lab/srai pull request #82
Opened 2022-11-03 10:57 UTC by RaczeQ

2022-11-17 09:39 UTC, RaczeQ commented
Closes #91, #68

2022-11-17 09:40 UTC, RaczeQ commented
Closes #68

2022-11-17 09:40 UTC, RaczeQ commented
Closes #91

2022-11-17 09:41 UTC, RaczeQ commented
Closes #69

2022-11-18 16:20 UTC, Calychas requested changes
Great work

2022-11-18 16:20 UTC, Calychas commented on docs/assets/css/palette.css
> +  --srai-brand-color: #01fdb1;
TBH, I feel a lot of eyestrain looking at this color in the docs. Maybe a little bit darker color like `#00eda5`?

2022-11-18 16:20 UTC, Calychas commented on mkdocs.yml
> +      accent: deep orange
probably should change from orange to `#150b5b` ?

2022-11-18 16:20 UTC, Calychas commented on mkdocs.yml
> +      accent: orange
Same here

2022-11-21 13:47 UTC, Calychas approved these changes

2022-11-23 16:07 UTC, merged